apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: shorya1853/results:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: voting
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: password
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: results
spec:
  selector:
    app: results
  ports:
    - port: 80
