# .github/workflows/docker-common.yml
name: Docker Common Steps

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      image-name:
        required: true
        type: string

jobs:
  docker-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Lint (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.service-path }}/Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}:${github.sha} ${{ inputs.service-path }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}:${github.sha}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}:${github.sha}
