name: Web Service CI

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  docker-web:
    uses: ./.github/workflows/docker-testing.yml
    working-directory: ./app
    with:
      service-path: ./web
      image-name: web
