name: Web Service CI

on:
  push:
    branches: [main]
    paths:
      - 'app/web/**'
      - '.github/workflows/web.yml'
  workflow_dispatch:

jobs:
  docker-web:
    runs-on: ubuntu-latest
    # uses: ./.github/workflows/docker-testing.yml
    # with:
    #   service-path: ./app/web
    #   image-name: web
    steps: 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin